// examples/sveltekit/src/routes/+page.svelte
<script lang="ts">import "../../../macro-suite/theme.css"; import { showcase } from "../../../macro-suite/showcase.sts";</script>
<main><h1>{showcase.title}</h1><p>{showcase.subtitle}</p><p class="hero">{showcase.hero}</p><section class="grid">{#each showcase.cards as card}<article><small>{card.kind}</small><h2>{card.name}</h2><p>{card.result}</p></article>{/each}</section></main>

// examples/tanstack-start/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { showcase } from "../../../macro-suite/showcase.sts";
export const Route = createFileRoute("/")({ component: Home });
function Home() {
  return (
    <main>
      <h1>{showcase.title}</h1>
      <p>{showcase.subtitle}</p>
      <p className="hero">{showcase.hero}</p>
      <section className="grid">
        {showcase.cards.map((card) => (
          <article key={card.name}>
            <small>{card.kind}</small>
            <h2>{card.name}</h2>
            <p>{card.result}</p>
          </article>
        ))}
      </section>
    </main>
  );
}
